services:
  math:
    build: .
    environment: 
      - SERVICE_NAME=math
      - NATS=nats://nats
  test:
    build: .
    environment: 
      - SERVICE_NAME=test
      - NATS=nats://nats

  shack:
    build: .
    environment: 
      - NATS=nats://nats
    ports: 
      - "3000:3000"
    command: npm run start

  nats:
    image: nats